hystrix:
  image: kbastani/hystrix-dashboard
  ports:
   - "7979:7979"
  links:
   - gateway
   - discovery
			cpu_shares: 30
			mem_limit: 100000000
discovery:
  image: kbastani/discovery-microservice
  ports:
   - "8761:8761"
configserver:
  image: kbastani/config-microservice
  ports:
   - "8888:8888"
  links:
   - discovery
			cpu_shares: 30
			mem_limit: 100000000
gateway:
  image: kbastani/api-gateway-microservice
  ports:
   - "10000:10000"
  links:
   - discovery
   - configserver
   - user
   - movie
   - recommendation
			cpu_shares: 30
			mem_limit: 100000000
user:
  image: kbastani/users-microservice
  links:
   - discovery
   - configserver
			cpu_shares: 30
			mem_limit: 100000000
movie:
  image: kbastani/movie-microservice
  links:
   - discovery
   - configserver
			cpu_shares: 30
			mem_limit: 100000000
recommendation:
  image: kbastani/recommendation-microservice
  links:
   - discovery
   - configserver
			cpu_shares: 30
			mem_limit: 100000000
moviesui:
  image: kbastani/movies-ui
  ports:
     - "9006:9006"
  links:
   - discovery
   - configserver
			cpu_shares: 30
			mem_limit: 100000000